name: Terraform Plan

on:
  workflow_dispatch:

env:  
  TERRAFORM_VERSION: "1.3.7"  
  TERRAFORM_DIRECTORY: "terraform"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:    
    runs-on: ubuntu-latest   
    environment: dev
    steps:
    
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.terraform_version }}
        terraform_wrapper: false

    - name: "Get Application Token"
      id: get_app_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.TECHDRIVEN_APP_CLIENTID }}
        private_key: ${{ secrets.TECHDRIVEN_APP_SECRET }}

    - name: Extend Git credentials
      uses: de-vri-es/setup-git-credentials@v2.0.10
      with:
        credentials: https://user:${{ steps.get_app_token.outputs.token }}@github.com

    - name: Log in using OIDC
      uses: azure/login@v1.4.7
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}        

    - name: Terraform Init      
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}
      shell: bash
      run: |
        terraform init -upgrade \
          -backend-config=storage_account_name=sablogterraform \
          -backend-config=container_name=terraformstate \
          -backend-config=key=demostate \
          -backend-config=resource_group_name=rg-blog-terraform \
          -backend-config=use_oidc=true
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        
    - name: Terraform Plan      
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}
      shell: bash
      run: |
        terraform plan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        
        
        